gallery/urls.py
from django.urls import path
from . import views

app_name = "gallery"
urlpatterns = [
    path("", views.GalleryList.as_view(), name="list"),
    path("<int:pk>", views.GalleryDetail.as_view(), name="details"),
    path("<int:pk>/images/<int:picture_pk>", views.PictureDetail.as_view(), name="picture-details")
    ]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("gallery.urls")),
]

gallery/models.py
from collections.abc import Iterable
from django.db import models


# Create your models here.
class TimestampedModel(models.Model):
    modified_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Gallery(TimestampedModel):
    title = models.CharField(max_length=200)

    def __str__(self): return self.title


class Picture(TimestampedModel):
    img = models.ImageField(upload_to="gallery/%Y/%m/%d")
    text = models.CharField(max_length=200)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

    def __str__(self): return self.text

    def save(self, force_insert: bool = ..., force_update: bool = ..., using: str | None = ...,
             update_fields: Iterable[str] | None = ...) -> None:
        super().save(force_insert, force_update, using, update_fields)

gallery/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Gallery, Picture


# Create your views here.
class GalleryList(ListView):
    model = Gallery
    paginate_by = 10


class GalleryDetail(DetailView):
    model = Gallery


class PictureDetail(DetailView):
    model = Picture

    def get_queryset(self):
        picture_pk = self.kwargs['picture_pk']
        objects = Picture.objects.filter(pk=picture_pk)
        return objects

gallery/templates/gallery/gallery_detail.html
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

{% block content %}
    <h1>{{ object.title|scream }}</h1>
    
    {% for image in object.picture_set.all %}
    
    <p>
        {% thumbnail image.img "250" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}

    </p>    
    {% endfor %}

{% endblock %}


def get_queryset(self):
model = self.kwargs['category']
return getattr(models, model).objects.all()

gallery/templates/gallery/gallery_list.html
{% block content %}
<h1>Lista galerii</h1>

{% if page_obj %}
{% for item in page_obj %}
<a href="{% url "gallery:details" item.id %}">
    <!--        <a href="gallery/<int:pk>">-->


    <div class="card mb-1">
        <div class="card-body">
            <p class="card-title">{{ item.title }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% if page_obj.has_other_pages %}
<div class="btn-group" role="group" aria-label="Item pagination">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
    {% endif %}

    {% for page_number in page_obj.paginator.page_range %}
    {% if page_obj.number == page_number %}
    <button class="btn btn-outline-primary active">
        <span>{{ page_number }} <span class="sr-only">(current)</span></span>
    </button>
    {% else %}
    <a href="?page={{ page_number }}" class="btn btn-outline-primary">
        {{ page_number }}
    </a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
    {% endif %}
</div>
{% endif %}
{% else %}
<p>No items found.</p>
{% endif %}


{% endblock %}

gallery/templates/gallery/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>


    <div class="container my-5">
    {% block content %}
      <h1>Hello, world!</h1>
      <div class="col-lg-8 px-0">
        <p class="fs-5">You've successfully loaded up the Bootstrap starter example. It includes <a href="https://getbootstrap.com/">Bootstrap 5</a> via the <a href="https://www.jsdelivr.com/package/npm/bootstrap">jsDelivr CDN</a> and includes an additional CSS and JS file for your own code.</p>
        <p>Feel free to download or copy-and-paste any parts of this example.</p>

        <hr class="col-1 my-4">

        <a href="https://getbootstrap.com" class="btn btn-primary">Read the Bootstrap docs</a>
        <a href="https://github.com/twbs/examples" class="btn btn-secondary">View on GitHub</a>
      </div>
    {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="main.js"></script>
  </body>
</html>

gallery/templates/gallery/picture_detail.html
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

{% block content %}
    <h1>{{ object.gallery.title|scream }}</h1>
    <img src="{{ object.img.url }}" alt="{{ object.text }}">


{% endblock %}